name = "b2a"
author = "Ripazha1333"
version = "0.4.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "360359f4dafa17379179ddf3fbe94275c7cdca6ecf8581ca4b801be2b6efbd43"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0"
